authors:
  carlos:
    name: Carlos Holguera
    description: Creator
    avatar: https://github.com/OWASP/mas-website/blob/main/docs/assets/carlos.jpg?raw=true
  sven:
    name: Sven Schleier
    description: Creator
    avatar: https://github.com/OWASP/mas-website/blob/main/docs/assets/sven.jpg?raw=true
