name: Build GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.actor == 'cpholguera' || github.actor == 'sushi2k' || github.actor == 'TheDauntless'
    steps:
      - name: Call reusable build workflow and deploy
        uses: ./.github/workflows/build-website-reusable.yml
        with:
          deploy: true